language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - env: CARGO-TRAVIS
  fast_finish: true
  include:
  - rust: stable
    env: RUSTFMT
    install:
      - rustup component add rustfmt
    script:
      - cargo fmt -- --check
  - rust: stable
    env: CLIPPY
    install:
      - rustup component add clippy
    script:
      - cargo clippy -- -D clippy
